version: "3"
services:
    redis-docker:
        image: redis:latest
        command: redis-server --port 6379
        container_name: "docker-redis"
        volumes:
            - ./docker-redis-data/redis:/data
        labels:
            - "name=redis"
            - "mode=standalone"
        ports:
            - 6379:6379