server:
  port: 8080

spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/../db/uni
#    username: sa
#    password: 1234
#    driver-class-name: org.h2.Driver
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: dryrain
    password: 1234
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

  redis:
    host: localhost
    port: 6379

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace

jwt:
  token:
    key: uni-Yeah~